### PR TITLE
Highlights the selected and todays month and year

### PR DESCRIPTION
**Pull request by benjamin-albert**
This pull request is a milestone for me, it includes the main feature that was missing and prevented me from using the open source version at work.

This month picker is supposed to replace a `<div>` tag with 2 `<select>` menus and three buttons (choose, today, and close).

This thing is terrible, so I was assignments to replace the date and month picker in our produces.

When I first showed the Month Picker to the support team the number one problem was that they were  spending to much time finding the selected month and then choosing the next month.

This was a big problem, especially when the two select menus it's supposed to replace defaulted to the selected month and year.

The month and year highlighting uses the same css classes that Datepicker uses to highlight today and the selected date:
<ul>
<li><b>ui-state-highlight</b> for today's month.
<li><b>ui-state-active</b> for the selected month.
</ul>

This means that this feature should instantly fit into the users existing themes and they can easily customize it using the <a href='http://jqueryui.com/themeroller/'>ThemeRoller</a> tool.

The best part about this feature is that you can instantly enjoy it once the user upgrades to the latest version (see for yourself in the updated <a href='http://jsfiddle.net/benjamin_albert/pgwozta6/'>fiddle</a>).

I've also written a test for this feature that also makes sure the month is not highlighted if it is out of the min/max bounds (see the new test: Today and selected months are highlighted).

Keeping the minified output small while not sacrificing readability (I wouldn't mind a review on that) is a top priority of mine.

So this pull request includes some code refactoring that makes the minified file smaller
even with all the new feature I've added it's almost half a kilobyte smaller than 2.2 (before I started contributing).

This was achieved by:
<ul>
<li>Slightly shortening the error messages <b>(please tell me what you think)</b>.</li>
<li>A new aproceh to triggering events that doesn't require us to specify OnAfterFooBar: $noop in the options hash and allows the user to remove an event by passing in the null (see the _event function).</li>
<li>Helping UglifyJS with <a href='https://github.com/mishoo/UglifyJS2#mangler-options'>variable Mangling</a> (shortening the variable names) by declaring a var for propertied that are repeatedly used through out a function.</li>
</ul>

I also fixed a couple of typos in the <a href='http://jsfiddle.net/benjamin_albert/pgwozta6/'>fiddle</a>.

### CODE REVIEW

**Comment by KidSysco** [comment]
Great work again Benjamin! I noticed one small thing, test 16 fails in IE 9 - 11 but passes in Edge.

I can merge if you want now and let you look at it later or I can wait to merge if it is easier.

Let me know what you want to do.

Thanks!

r.

**Comment by benjamin-albert** [comment]
Good thing you caught this.

I develop no Mac at home so I test on Safari Chrome Firefox and PhantomJS but I don't have any convenient access to Internet explorer (I don't want to setup a VM or ask for someone else's windows machine just to test in this crappy browser).

Luckily I'm at work now and I have windows here let me take a look and I'll update you.

**Comment by benjamin-albert** [comment]
I've refactored the `_setDisabledState` method do that it will only disable input and button tags (elements that support the diabled property and make sense as a button). So I added a test for this behavior.

In the test I was asserting that the `disabled` property is `undefined`, but internet explorer normolizes the disabled property's value, for example:
<pre>
ImgButton.disabled = 'I love internet explorer :(';
// will log true in IE and 'I love internet explorer :('
// in every other browser.
console.log(ImgButton.disabled); 
</pre>

The tests was fixed by making sure that the disabled property is not equal to true after disabling the field.

BTW I didn't mention this in the original comment I also fixed a bug that caused the `month-picker-disabled` to not be applied to the input field and added a test for this.

**Comment by KidSysco** [comment]
All tests are passing nicely now, great work, thanks for the update!

**Pull request merged**
