### PR TITLE
Added IsRTL, Button, ShowOn and ButtonIcon options + added Open, Close and Trigger methods

### PR DESCRIPTION
**Pull request by benjamin-albert**
Hi,

This pull includes the rest of the features mentioned in #16 and a fix for the Month input bug.

I've added a couple of new options:
<ul>
<li><b>IsRTL</b> allows setting the menu's run direction as right to left (a separate <a href='http://jsfiddle.net/benjamin_albert/teashz0y/2/'>fiddle</a> is required for this).</li> 
<li><b>Button</b> which every detail about the icon (see documentation for more details).</li>
<li><b>ShowOn</b> which allows setting the menu to open on both clicking the button and focusing on the associated input field.</li>
<li><b>ButtonIcon</b> which allows setting a different primary <a href='http://api.jqueryui.com/theming/icons/'>icon class name</a> for the default icon.</li>
</ul>

I've also added some new methods:
<ul>
<li><b>Open</b> which allows externally opening the menu (useful in cases where the textfield and menu dynamically created on demand, see documentation for more details).</li>
<li><b>Toggle</b>  opens or closes the menu.</li>
<li><b>Close</b> which closes the menu.</li>
</ul>

I've also added some new events:
<ul>
<li><b>OnBeforeMenuClose</b>  triggered before the Month Picker menu will close, and it allows you to prevent the menu from closing (required for the Open method to be of any use to someone).</li>
<li><b>OnBeforeMenuOpen</b>  triggered before the Month Picker menu will open and it allows you to prevent the menu from opening.</li>
<li><b>OnAfterSetDisabled</b>  triggered after the Disabled option was changed.</li>
</ul>
I've also made opening the menu focus on the associated input field and pressing next and previous keeps the field in focus. 

When I first added the new code to the <a href='http://jsfiddle.net/benjamin_albert/yjgcjovg/6/'>new fiddle</a> I broke the '#IconDemo icon removed after init.'

The test was checking if the icon was removed from the DOM but because I allow using existing external elements as buttons I don't want to remove them so instead I hide them.

So I changed line number 809 to look only for visible elements and it passes.

When I finish implementing the rest of the features I need to use the open source version in my company I will help writing tests and examples for the many use cases I designed the Button option to support.

### CODE REVIEW

**Comment by KidSysco** [comment]
Very nice work, I adjusted my tests. I will write some tests for the new features and hit you up if I have any questions! THANKS!

**Comment by KidSysco** [comment]
In the fiddle demonstrating the RtL support, it looks like the years are showing left aligned perhaps. Thought I might have you take a look at it Benjamin. Love the Hebrew BTW!

**Comment by KidSysco** [comment]
My jewish friends are very impressed!

**Comment by benjamin-albert** [comment]
Yes I know.

The reason for this is that in line 5 of the fiddle's css I've added `width: 45px;` because the buttons are don't have a consistent width.

If you comment out that rule the years will be aligned to the center.

I'll see if there is anyway to handle cases when the translation results in inconsistent button sizes and that the years will stick to the middle.

**Comment by benjamin-albert** [comment]
Setting `width: 90%;` seems to give better results.

See: http://jsfiddle.net/benjamin_albert/teashz0y/3/

**Comment by KidSysco** [comment]
That is looking really good!

**Comment by KidSysco** [comment]
I had no idea Hebrew was Right to Left.

**Pull request merged**
