### PR TITLE
Fixed incorrect i18n documentation, and added Position option

### PR DESCRIPTION
**Pull request by benjamin-albert**
Hi,

I really like what you and the other contributors are doing with your month picker widget but I had to make some modifications to use it in my company's products.

The modified version I'm using in my company is not good enough to make open source but I'm hoping to find the time to polish the features iv'e added and I'm hoping my company will eventually use the open source (your) version.

I will open issues on your repo with all of the features I'm planning to implement, here are a couple:
<ol>
<li> Add an show/hide animation option (my company prefers a simple fade in/out animation).</li>
<li>Add a Format option.</li>
</ol>

Here is a summery of the changes I've made so far:
<ol>
<li>Fixed incorrect `i18n` documentation and added missing `<` to the script and link tags in README.md.</li>
<li> If <a href='http://api.jqueryui.com/position/'>jQuery UI .position() plugin</a> is loaded (it's optional) it will be used for positioning this solves an issue we had in my company's products that the menu would be partially hidden when it overflows the window in any direction.

If the `.position()` plugin is not loaded it will fallback to the old position logic.
</li>
<li> Added a Position option, If jQuery UI position plugin is loaded the user can specify exactly how they would like menu to be positioned using the jQuery UI position options (see README.md for more details).
</li>
<li> Replaced `this._super('_setOption', key, value);` with `this._super(key, value);` so that we don't end up having a `_setOption` option with a value of the last key being set.

Fixing this issue allowed deleting unnecessary explicit assignment making the method smaller and cleaner.
</li>
<li> All On callback options will have a default value of `$.noop` (an empty function) this allows us to delete the `_isFunction()` method and shorten the `ClearAllCallbacks` method.

BTW: If you are using jQuery and you need to check if something is a function use <a href='https://api.jquery.com/jQuery.isFunction/'>$.isFunction()</a>.
</li>
<li> The minified output is about 1KB smaller.</li>

I didn't update the jsfiddle in the README.md so you can just use my version and copy
<a href='http://jsfiddle.net/benjamin_albert/9f3j3fey/1/'>my jsfiddle</a>.

This is my first pull request so hope everything will go ok.
Thank for an amazing plugin!

### CODE REVIEW

**Comment by KidSysco** [comment]
You have shown a strong understanding of jQuery, UI, the Widget Factory, and several good techniques that I could learn from. I have tested this pretty well and reviewed the code extensively. I expect to merge this pull request within the week. Thank you for your good work! Stop by anytime!

**Comment by KidSysco** [comment]
I went ahead and updated the fiddle with your code, tested the position feature you added and it all seems to work very well! I only added one simple assertion test but we can add more later if needed. The important part is that no existing test broke ensuring that we did not break or change any public APIs with this merge. All developments using this plugin should be able to upgrade without worry. This is great work here, I am merging now.

**Comment by KidSysco** [comment]
Added 4 more tests today for position, 1 of which verifies that the menu is fully visible on the page for the X axis. Y axis will come next! I really like the .position() support!

**Comment by benjamin-albert** [comment]
I'm getting `Error: pushFailure() assertion outside test context, was QUnit.start@http://code.jquery.com/qunit/qunit-1.11.0.js:452:1` when I click the Choose a month (`#PositionDemo`) text input.

I'm getting this error in three different browsers (FirefoxDeveloperEdition, Chrome and Safari).

screen shot 2015-09-30 at 7 42 07 pm

I'll see if there's anything I can do after I open an issue explaining what I want to do next.

**Comment by KidSysco** [comment]
Thank you very much once again. I have adjusted the unit test so that it should behave better now. Good catch, thank you for helping us keep this plugin rock solid and trustworthy!

**Comment by KidSysco** [comment]
Sure, open up more issues and make suggestions! I will create unit tests for your ideas and ensure that no previous tests get broken as a result of your new code!

**Pull request merged**
