### PR TITLE
Clear alt format field value on "Clear" method call

### PR DESCRIPTION
**Pull request by Yakim**

### CODE REVIEW

**Comment by benjamin-albert** [comment]
Thank you for opening a pull request and help make this plugin better for everyone!

This change looks good to me, but we should really have a unit test for this.
@Yakim  Do you want to try to write the test yourself, or would you prefer that we write the test?

I personally learned a lot from writing unit test for this project and it's changed the way I write JavaScript everywhere.

We would be glad to help you if you want to try and write the test.

**Comment by KidSysco** [comment]
I was thinking the same thing. I would be willing to write the test as well. Let me know how you guys want to handle it!

**Comment by KidSysco** [comment]
ok that must be a "no".

I will write a unit test for this then commit this week.

**Comment by benjamin-albert** [comment]
@KidSysco I guess we can close this pull request?

**Comment by KidSysco** [comment]
yep!

**Pull request closed without merging**
