### PR TITLE
Adds MonthFormat and Animation options + GetSelectedDate and Validate methods

### PR DESCRIPTION
**Pull request by benjamin-albert**
Hi,

This is a pull request for #16.

I've added a couple of new options:
<ul>
<li>MonthFormat which uses <a href='http://api.jqueryui.com/datepicker/#utility-formatDate'>$.datepicker.formatDate()</a> and <a href='http://api.jqueryui.com/datepicker/#utility-parseDate'>$.datepicker.parseDate()</a> to format, parse and create the input mask. You can also use a third party library for parsing and formatting (see the new README.md).</li> 

<li>Animation which allows you to specify the animation to use in both opening and closing the menu, but I also included ShowAnim and HideAnim for consistency with datepciker and to allow you to have different animations for opening and closing the menu.</li>

<li>
Duration which allows specifying the animations speed.
</li>
</ul>

I've also added some new methods:
<ul>
<li>GetSelectedDate which return the month as a JavaScript Date object.</li>
<li>Validate an alternative for GetSelectedMonthYear which validates the input and return the selected month as a JavaScript Date object.</li>
</ul>

I've also added some usability features:
<ul>
<li>The default animation is fadeToggle and the default speed is 400ms (to match datepicker's behavior).
<li>Pressing escape hides the menu.</li>
<li>Pressing enter selects the current month.</li>
</ul>

All events `this` new refer to the associated input field, it would be grate if you can add some tests for `$(this)...`.

When I first added the new code to the <a href='http://jsfiddle.net/benjamin_albert/z0edh4pt/4/'>new fiddle</a> I broke a GetSelectedMonthYear unit test that tested that the return value was '2/2012' and the new code was returning '02/2012' (because I was using the MonthFormat option).

I have to admit that when I first refactored this method I thought it use to be a private method that was made public because It had all of that validate code which I thought had nothing to do with the method.

But when I first looked at the documentation I was surprised because:
<ul>
<li>The name is misleading. There's no way someone how didn't read the docs will know that method performs visual validation.</li>
<li>Except for comparing the value a with specific string the value returned is kind of useless.</li>
<li>The docs say it focuses on the invalid value but I did't see anything like that in the code (perhaps we should remove this from the docs until we actually implement this).
</ul>

So I added the Validate method which I believe better reflects what it does and returns a Date that you can interact with and get exactly what you want out of it without having to parse a string or use the lengthy GetSelectedMonth and GetSelectedYear methods.

I would appreciate it if you can look at my new documentation and tell me if I have any typos (my spelling isn't perfect).

### CODE REVIEW

**Comment by KidSysco** [comment]
Benjamin! You are a rock star! I was out of town on travel all weekend and just got back. Give me a few days to soak this up then I will probably merge it in.

Keep it coming if you got more!

THANKS!

**Comment by KidSysco** [comment]
Nice fiddle you put together! Thats great! Woot! I love your work!

**Comment by benjamin-albert** [comment]
I'm glad to hear you're excited about my work.

I've just finished implementing the rest of the features in #16 you can take a look at the <a href='https://github.com/benjamin-albert/jquery-ui-month-picker/tree/2.5'>2.5</a> branch in my fork.

 I'll open a pull request with all the details when I finish testing, writing documentation and creating a fiddle.

**Comment by KidSysco** [comment]
I really like the Date Picker formatting and parsing. That is some great work that really shows strong understanding of the jQuery UI internals. I saw you did some extra work there to ensure unit tests were not broken, that is great work too. It is a pleasure to work with you Benjamin, you are a true professional. I am going to merge this and close it out now. Then I will update the fiddle.

**Pull request merged**
