### PR TITLE
🐛 Buttons disabled check uses boolean

### LINKED ISSUE #72: Next and Previous Buttons disabled when using jQuery UI 1.12
Hi Folks, 
I have a small tester here: http://kompsoft.de/test/eqdkp/ajax/calendarmonthcheck/demos/basic-views.html

if you click on the month Name in the Header, the monthpicker Shows up. All working. Only Thing currently not working is the previous and next button. These Buttons are disabled.

Any idea? Maybe fullcalendar intereferes with the Dates?

### PR DESCRIPTION
**Pull request by ComiR**
Fixes #72

I also changed the comparison types to strict.

### CODE REVIEW

**Comment by xenogew** [comment]
@KidSysco When will you plan to accept this Pull Request? I got struck with the Next/Previous disabled issue with your latest release.

**Comment by KidSysco** [comment]
Very interesting, give us some time to look at it here and we will keep you posted.

**Comment by ComiR** [comment]
Wow - didn't even remember this PR anymore. Pretty long time ignoring it.
I only was triggered to write this because you asked to "give us some time to look at it" - this PR is from the beginning of NOVEMBER LAST YEAR!
Please don't be offended - it just made my day 🤣.

**Comment by benjamin-albert** [comment]
We already have #73 which addresses this issue and other visual glitches that jQuery UI 1.12 introduces.

**Pull request closed without merging**
